### ISSUE TITLE
Incohérence entre la pagination du forum et des mps

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#2597]
[Reporté par Flori@n.B sur le forum](https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=29#p53982) :

> J'ai remarqué quelque chose qui relève plus de la cohérence, que d'un réel bug. Avec la dernière version du site, sur les forums quand on passe en version mobile (ou qu'on réduit la fenêtre), les termes « _suivante_ »/« _précédente_ » pour les pages ont disparu (ce que je trouve plutôt cool !). Cependant, sur les MPs ont reste sur l'ancien comportement.. c'est assez dommage !

Ce bug est bien présent dans la v1.7b ainsi que dans la v1.8-RC1 !

**Comment by GerardPaligot** [comment]
Je rajoute des informations techniques : En fait, la pagination sur la liste des membres, la liste des MP et la liste des messages d'un MP sont différents des autres paginations puisqu'ils ont une approche CBV. Nous coexistons pour le moment avec 2 templates de pagination à cause de ça.

**Comment by Situphen** [comment]
Si du coup la personne qui fait la PR peut indiquer le lien entre les deux gabarits (= templates) en commentaires, ce serait cool ! Si vous ne savez pas comment faire, pingez moi ! :)

**Comment by Eskimon** [comment]
Pour le template :
-  "_suivante_ est toujours affiche" c'est la : https://github.com/zestedesavoir/zds-site/blob/dev/templates/misc/pagination.part.html
-  "_suivante_ n'est pas visible sur mobile" c'est la : https://github.com/zestedesavoir/zds-site/blob/dev/templates/misc/paginator.html

Jme tate a tagguer bug ou evolution... Je met Bug car on a un comportement pas aligne entre deux briques censée être identique.

**Comment by pierre-24** [comment]
Donc, sur la ZEP-12, on devrait employer "paginator", pour bien faire ?

**Comment by Situphen** [comment]
@Eskimon : non c'est l'inverse, c'est `paginator.html` qui n'a pas de `span` !

@pierre-24 : De toutes façons vous devriez utiliser `paginator.html` car c'est le template utilisé par les modules CBV.

---

Voir la PR #2449.

**Façon simple**

Mettre `<span>` et `</span>` autour de "Précédent" et "Suivant" dans le fichier `paginator.html`.

**Façon plus compliquée mais AMHA plus propre**

Enlever `<span>` et `</span>` autour de "Précédent" et "Suivant" dans le fichier `pagination.part.html`.

Modifier le fichier CSS pour remplacer ça :

``` scss
@media only screen and #{$media-mobile} {
            .pagination {
                li {
                    &.prev a,
                  &.next a {
                        min-width: 0px;
                        span {
                            display: none;
                        }
                    }
                }
            }
        }
```

Par ça :

``` scss
@media only screen and #{$media-mobile} {
            .pagination {
                li {
                    &.prev a,
                  &.next a {
                        min-width: 0px;
                        text-indent: -9999px;
                    }
                }
            }
        }
```
