### ISSUE TITLE
Migrer vers notre nouveau zmarkdown: Front-end

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#4390]
Ce ticket pour la migration vers le nouveau zmarkdown, côté frontend.

- [x] Implémenter un signal visual pour les liens/icône d'ancres sur les `<h1...6>`, cf https://beta.zestedesavoir.com/forums/sujet/10349/ancres-sur-les-titres/
- [x] Adapter les 'blocks' / 'panels'  de nouveaux types (neutre), nouvelles fonctionnalités (titres)
- [x] Implémenter les n° de ligne en CSS: https://github.com/zestedesavoir/zds-site/pull/4851
- [x] Corriger les (éventuelles) coquilles CSS dues aux incompatibilité entre pyzmd et zmd
- [x] Adapter les 'blocks' / 'panels' (info, question, erreur, etc) aux nouvelles classes, 
- [x]  `-> ![alt](image) <-` ne centre pas l'image
- [x] équations, vidéos en responsive
- [x] lorsque le code a une caption, il est centré 
![screenshot-2018-2-28 le deroulement d une requete introduction aux filtres et aux routes - creez votre site web avec asp ne](https://user-images.githubusercontent.com/1523653/36788340-dcdf1914-1c8d-11e8-8f34-75fc3b6afbe3.png)

**Comment by Situphen** [comment]
C'est une requête Ajax en asynchrone donc je suppose que c'est une XHR (on passe par jQuery c'est transparent). Je pense aussi que c'est une bonne idée de garder ça dans un premier temps (ça fonctionne et c'est plutôt rapide en général) !

**Comment by sandhose** [comment]
Honnêtement c'est plutôt facile à faire, ça serait dommage de s'en priver.

**Comment by Situphen** [comment]
Peut-être mais comme toute modification c'est source de bugs. Il y a aura déjà assez de problèmes avec le zmarkdown, pas la peine d'en rajouter :)

**Comment by Situphen** [comment]
Pour que le site soit full responsive design (qu'aucun n'éléments ne débordent sur mobile), il faut rajouter ce CSS (certains bouts y sont peut-être déjà) :

```css
/* pour les tableaux */
.table-wrapper {
    overflow-x: auto;
}

/* pour les vidéos */
.video-container {
    margin: 0 auto;
}
.video-wrapper {
    position: relative;
}
.video-wrapper iframe {
    position:absolute;
    width: 100%;
    height: 100%;
}

/* pour les iframes (pour l'instant jsFiddle et le player de l'INA */
.iframe-wrapper {
    overflow-x: auto;
}

/* pour les maths */
.inlineMathDouble {
    overflow-x: auto;
}
```
