### ISSUE TITLE
Changement des smileys

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#4404]
Bonjour,

Buddy a mis à disposition de magnifique [smiley Clem](https://zestedesavoir.com/forums/sujet/538/clem-sur-le-devant-de-la-scene/?page=15#p105025). S'il n'y a aucun retour négatif, je fais une PR.

Je lui ai envoyé un MP à Buddy pour le prévenir.

A-312.

**Comment by A-312** [comment]
> Syntaxe | Smiley | Image 1px/1pt | Image 4px/1pt
> ------|-----|-----|-----
> `:)` | :) | ![:)](http://zestedesavoir.com/media/galleries/860/d3ae250a-1224-4fe6-ba6c-0bc6fc6f3b1b.png) | ![:)](http://zestedesavoir.com/media/galleries/3117/23e7c656-bdce-4ba0-90d1-4d52c5ce4ecd.png)
> `:D` | :D | ![:D](http://zestedesavoir.com/media/galleries/860/9fdf8a8f-4eef-4aaa-aa04-3a19f2022745.png) | ![:D](http://zestedesavoir.com/media/galleries/3117/ee60a541-97d3-4fd3-b6b1-cd0c3a57f6c4.png)
> `;)` | ;) | ![;)](http://zestedesavoir.com/media/galleries/860/2d26f628-66c0-4d98-8b8d-f3bdfab3ac72.png) | ![;)](http://zestedesavoir.com/media/galleries/3117/ef46a490-827d-498a-8e7d-2b0dca29e0e8.png)
> `:p` | :p | ![:p](http://zestedesavoir.com/media/galleries/860/77efc990-2a77-4612-907e-7880c1f80ae8.png) | ![:p](http://zestedesavoir.com/media/galleries/3117/a3ca5fab-c3ef-423b-a028-456bc858ca0b.png)
> `:lol:` | :lol: | ![:lol:](http://zestedesavoir.com/media/galleries/860/0bc88b47-311d-4da6-b28c-749b0f14f0ed.gif) | ![:lol:](http://zestedesavoir.com/media/galleries/3117/a0136e53-320c-467b-85d8-32f567ccd3ea.gif)
> `:euh:` | :euh: | ![:euh:](http://zestedesavoir.com/media/galleries/860/f0afa9d1-2aed-4d73-ab1c-2c1afa6feced.gif) | ![:euh:](http://zestedesavoir.com/media/galleries/3117/e631ff1c-d5c2-41fc-b4e2-b33ebfd97c98.gif)
> `:(` | :( | ![:(](http://zestedesavoir.com/media/galleries/860/2089fbb1-5f8c-435a-b7d4-04c774a73c23.png) | ![:(](http://zestedesavoir.com/media/galleries/3117/04276309-aa1a-4e60-ac56-b9924bf3da47.png)
> `:o` | :o | ![:o](http://zestedesavoir.com/media/galleries/860/ea097dbf-34ec-4bab-a572-815353e20582.png) | ![:o](http://zestedesavoir.com/media/galleries/3117/327b7ff8-ed49-47d6-9a02-a4c9cfc5998b.png)
> `:colere2:` | :colere2: | ![:colere2:](http://zestedesavoir.com/media/galleries/860/08348de4-f0ec-4e6f-b2b8-fd022480a1bc.png) | ![:colere2:](http://zestedesavoir.com/media/galleries/3117/7ffa7e8a-44d4-4bff-80fb-33af60525f1c.png)
> `o_O` | o_O | ![o_O](http://zestedesavoir.com/media/galleries/860/cd1941b0-b31a-4a06-bd34-349b66c6d3ca.gif) | ![o_O](http://zestedesavoir.com/media/galleries/3117/35392bae-4be7-4f10-bd52-4cae5be9fc86.gif)
> `^^` | ^^ | ![^^](http://zestedesavoir.com/media/galleries/860/211bdb02-ca18-4d1d-be36-8456310fdce3.png) | ![^^](http://zestedesavoir.com/media/galleries/3117/f2eda0a5-4867-4beb-845b-7376783d8953.png)
> `:-°` | :-° | ![:-°](http://zestedesavoir.com/media/galleries/860/28d55fcf-175e-4b3c-9243-7f66c9af8437.png) | ![:-°](http://zestedesavoir.com/media/galleries/3117/0ff5bdc5-072e-45b6-b4fd-58fa98569cee.png)
> `:ange:` | :ange: | ![:ange:](http://zestedesavoir.com/media/galleries/860/5344d732-d017-4231-a9c7-ed1a03fb5a4b.png) | ![:ange:](http://zestedesavoir.com/media/galleries/3117/9c28dd69-cca3-4ed5-a9d6-1d349ab96aa8.png)
> `:colere:` | :colere: | ![:colere:](http://zestedesavoir.com/media/galleries/860/2f856336-9ccd-46e6-a7d0-98b20c11c3fc.gif) | ![:colere:](http://zestedesavoir.com/media/galleries/3117/b4346165-ab7a-430b-8ab5-7aabc6922bbc.gif)
> `:diable:` | :diable: | ![:diable:](http://zestedesavoir.com/media/galleries/860/72bbe717-eee6-48c3-838e-d0ac5ed5bcf2.png) | ![:diable:](http://zestedesavoir.com/media/galleries/3117/a4e34733-52d5-419a-8c8e-dfd859c9ea19.png)
> `:magicien:` | :magicien: | ![:magicien:](http://zestedesavoir.com/media/galleries/860/ab023c32-6474-431d-a0eb-686afc41afc7.png) | ![:magicien:](http://zestedesavoir.com/media/galleries/3117/abf7900b-a40e-41f2-a93a-a80b2b0fa665.png)
> `:ninja:` | :ninja: | ![:ninja:](http://zestedesavoir.com/media/galleries/860/85512231-9eb1-4a43-a62f-20a328c80740.gif) | ![:ninja:](http://zestedesavoir.com/media/galleries/3117/f6b3e7cc-9298-4047-88c7-0f0330cbac6e.gif)
> `>_<` | >_< | ![>_<](http://zestedesavoir.com/media/galleries/860/401fcb15-e394-4d93-9baa-2d3a4cb18c52.png) | ![>_<](http://zestedesavoir.com/media/galleries/3117/ca4ccde2-5179-4fab-b5d0-a01b1811fdc4.png)
> `:pirate:` | :pirate: | ![:pirate:](http://zestedesavoir.com/media/galleries/860/918825e9-2431-4a86-ba54-a9a3056e8daf.png) | ![:pirate:](http://zestedesavoir.com/media/galleries/3117/6ce92462-be6f-4694-9f19-42806032bf9d.png)
> `:'(` | :'( | ![:'(](http://zestedesavoir.com/media/galleries/860/3a459155-e18b-48b6-8615-e2b73d2d7634.png) | ![:'(](http://zestedesavoir.com/media/galleries/3117/013e97d6-f078-4a4d-a911-360192e943c0.png)
> `:honte:` | :honte: | ![:honte:](http://zestedesavoir.com/media/galleries/860/b7303439-0891-4892-8744-c528a8c1ed10.png) | ![:honte:](http://zestedesavoir.com/media/galleries/3117/3fc0ce3a-4aee-4ee3-b706-fa896d3fa0ba.png)
> `:soleil:` | :soleil: | ![:soleil:](http://zestedesavoir.com/media/galleries/860/911f9593-2de4-4dfc-bac8-5c65173c797a.png) | ![:soleil:](http://zestedesavoir.com/media/galleries/3117/3d6e0c6d-6e97-4460-88bf-0473515e6984.png)
> `:waw:` | :waw: | ![:waw:](http://zestedesavoir.com/media/galleries/860/d544d6f6-dc49-4850-a56e-359c9a9fa0ce.png) | ![:waw:](http://zestedesavoir.com/media/galleries/3117/ee431b6d-79ed-404f-8dab-5ef581443daf.png)
> `:zorro:` | :zorro: | ![:zorro:](http://zestedesavoir.com/media/galleries/860/35e91ec7-f428-45d0-9c63-2a8759076873.png) | ![:zorro:](http://zestedesavoir.com/media/galleries/3117/a3779bf7-95af-4ab3-8848-fa59f78a94ab.png)
> `^(;,;)^` | ^(;,;)^ | […] | […]
> 
> Changements opérés :
> 
> Avant | Après
> ------|-----
> ![:diable:](http://zestedesavoir.com/media/galleries/860/c9a1a08b-02a3-499d-aeaf-b3192cad05b4.png) | ![:diable:](http://zestedesavoir.com/media/galleries/860/72bbe717-eee6-48c3-838e-d0ac5ed5bcf2.png)
> ![:'(](http://zestedesavoir.com/media/galleries/860/a5fdc98b-95b1-4097-aadc-bf462cb6f3e6.png) | ![:'(](http://zestedesavoir.com/media/galleries/860/3a459155-e18b-48b6-8615-e2b73d2d7634.png)
> ![:magicien:](http://zestedesavoir.com/media/galleries/860/c249d40d-b73a-482b-9633-c3e8c1bcfbf5.png) | ![:magicien:](http://zestedesavoir.com/media/galleries/860/ab023c32-6474-431d-a0eb-686afc41afc7.png)

> V1 | V2 | V3
> ------|-----|-----
> ![:'(](http://zestedesavoir.com/media/galleries/860/a5fdc98b-95b1-4097-aadc-bf462cb6f3e6.png) [...] | ![:'(](http://zestedesavoir.com/media/galleries/860/3a459155-e18b-48b6-8615-e2b73d2d7634.png) ![:'(](http://zestedesavoir.com/media/galleries/3117/013e97d6-f078-4a4d-a911-360192e943c0.png) | ![:'(](http://zestedesavoir.com/media/galleries/860/f813a830-c9ee-441a-9abd-126240b2afb8.png) ![:'(](http://zestedesavoir.com/media/galleries/3117/5bf36d7d-a7b5-4d3b-843d-2ee3faafa48b.png)

**Comment by Situphen** [comment]
Il faudrait faire une recherche mais de mémoire la solution trouvée pour satisfaire à la fois ceux pour les nouveaux smiley et ceux pour garder les actuels était de laisser le choix au niveau des paramètres.

**Comment by A-312** [comment]
@Situphen C'est-à-dire ?

L'utilisateur choisi ce qui s'affiche chez lui c'est ça ?

Comment on fait ? On utilise un fichier css et un background-image au lieu d'une balise img ? Et en change le fichier css en fonction du paramètre ou on applique une className au body pour choisir quels règles css établir ?

**Comment by pierre-24** [comment]
Quid des smileys déjà insérés "en dur" (par le markdown) et qui ne bougerons pas (genre dans les messages de forums et les contenus, le HTML est sauvé et utilisé) ?

**Comment by rezemika** [comment]
Peut-être avec une option dans le markdown pour choisir le groupe d'images à utiliser pour les smileys ? Même si ça implique de refaire le rendu à chaque fois...

**Comment by A-312** [comment]
En sprite (le css est optimisable) :

![sprites](https://user-images.githubusercontent.com/18501150/28240135-c3b69e0a-697b-11e7-9d21-897b8ee1b7be.png)

```css
.ange{width:41px;height:27px;background: url("sprites.png") no-repeat -0px -0px;}
.clin{width:19px;height:27px;background: url("sprites.png") no-repeat -99px -25px;}
.cthulhu{width:25px;height:21px;background: url("sprites.png") no-repeat -0px -105px;}
.diable{width:27px;height:22px;background: url("sprites.png") no-repeat -66px -0px;}
.heureux{width:19px;height:26px;background: url("sprites.png") no-repeat -31px -79px;}
.hihi{width:19px;height:27px;background: url("sprites.png") no-repeat -34px -52px;}
.honte{width:20px;height:23px;background: url("sprites.png") no-repeat -50px -79px;}
.huh{width:20px;height:25px;background: url("sprites.png") no-repeat -72px -52px;}
.langue{width:19px;height:26px;background: url("sprites.png") no-repeat -53px -52px;}
.magicien{width:26px;height:27px;background: url("sprites.png") no-repeat -0px -53px;}
.mechant{width:19px;height:23px;background: url("sprites.png") no-repeat -70px -79px;}
.pinch{width:21px;height:24px;background: url("sprites.png") no-repeat -93px -0px;}
.pirate{width:25px;height:25px;background: url("sprites.png") no-repeat -41px -0px;}
.pleure{width:27px;height:25px;background: url("sprites.png") no-repeat -0px -80px;}
.siffle{width:19px;height:27px;background: url("sprites.png") no-repeat -60px -25px;}
.smile{width:19px;height:27px;background: url("sprites.png") no-repeat -41px -25px;}
.soleil{width:20px;height:25px;background: url("sprites.png") no-repeat -92px -52px;}
.triste{width:19px;height:23px;background: url("sprites.png") no-repeat -50px -102px;}
.waw{width:20px;height:26px;background: url("sprites.png") no-repeat -79px -25px;}
.zorro{width:33px;height:26px;background: url("sprites.png") no-repeat -0px -27px;}
```

Il manque (les gifs) : angry.gif , blank.gif , ninja.gif , rire.gif et unsure.gif
