### ISSUE TITLE
Trop d'espace sur la balise spoiler ?

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#4457]
Bonjour,

J'ai l'impression qu'il y a trop d'espace entre le .spoiler-title et le .spoiler, la règle [margin-top#L194](https://github.com/zestedesavoir/zds-site/blob/24b5cd19c0c800ac3a0c5e3f46c85004d2b31302/assets/scss/layout/_content.scss#L194) n'est pas prise en compte. S'agit-il d'une régression dû à une factorisation du CSS ?

Ce sont les deux premières propriétés qui ne sont pas prise en compte.

```css
.spoiler {
  margin-top: 0;
  padding-left: 15px;
  background: #EEE;
}
```

A-312.

Il faudrait ajouter un !important au margin-top et padding-left ou déplacer la déclaration de la règle.
