### ISSUE TITLE
Améliorer le mode Halloween

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#4771]
Bonjour,

Pour Halloween 2018, il faudrait améliorer le mode en modifiant les couleurs du css : 

https://zestedesavoir.com/forums/sujet/7095/le-theme-dhalloween/?page=1#p165439

```css
.flexpage .flexpage-header {
    background: #5F0B00;
}

.header-container header {
    background: #3F0B00;
}

.header-container .header-logo-link:hover {
    background-color: #763E36;
}

.header-container .header-menu-list > li > a.active, .header-container .header-menu-list > li > a:focus, .header-container .header-menu-list > li > a:hover {
    background: #763E36;
}

.dropdown .dropdown-link-all:first-child {
    border-bottom: 1px solid #F8AD32;
}

.dropdown {
    background-color: #763E36;
}

.dropdown .dropdown-list > li ul li a {
    color: #F8AD32;
}

.page-footer {
    background: #3F0B00;
}

.content-item.write-tutorial {
    background-color: #3F0B00;
    border-color: #3F0B00;
}

.content-item.write-tutorial .btn-write-tutorial {
    background-color: hsla(0,0%,100%,.15);
}

.logbox .notifs-links .ico-link.active, .logbox .notifs-links .ico-link:focus, .logbox .notifs-links .ico-link:hover {
    background: #763E36;
}

.logbox .dropdown .dropdown-list li a:focus, .logbox .dropdown .dropdown-list li a:hover, .logbox .dropdown li a:focus, .logbox .dropdown li a:hover {
    background-color: #470A00;
}

.logbox .dropdown .dropdown-title {
    border-bottom: 1px solid #5F0B00;
    background-color: #763E36;
}

.dropdown .dropdown-link-all {
    border-top: 1px solid #5F0B00;
    background-color: #763E36;
}

.dropdown .dropdown-link-all:focus, .dropdown .dropdown-link-all:hover {
    color: #F8AD32;
    background-color: #470A00;
    border-top: 1px solid #5F0B00;
}

.logbox .dropdown, .logbox .dropdown .dropdown-list {
    background-color: #5F0B00;
}

.logbox .dropdown .dropdown-list li:nth-child(2n+1), .logbox .dropdown .dropdown-list li:nth-child(2n+1) form button, .logbox .dropdown li:nth-child(2n+1), .logbox .dropdown li:nth-child(2n+1) form button {
    background-color: #4F0B00;
}
```
