### ISSUE TITLE
[EasyMDE] Amélioration de la coloration des balises de citations

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5645]
![image](https://user-images.githubusercontent.com/18501150/75623764-b73e3a80-5bad-11ea-8a20-49e9298282b9.png)

```css
.cm-quote {
    color: #777;
}
```
