### ISSUE TITLE
Réintroduction de `linenostart` et `hl_lines`

### ISSUE THREAD

**Issue by StaloneLab** [zestedesavoir/zds-site#5846]
## Description du problème

La version 9.1 du moteur de rendu ZMarkdown voit le retour des fonctionnalités `hl_lines` et `linenostart` ; cependant, ce support prend une forme différente de ce qu'elle était auparavant.

Par conséquent, il est nécessaire de modifier le CSS pour réintroduire ces fonctionnalités. Je tiens à préciser qu'**aucun changement de cette version n'est bloquant**, la mise à jour du module peut donc être indépendante des modifications requises par ce ticket.

## Comment sont maintenant rendus les blocs de code ?

Pour quiconque souhaiterais s'essayer à ce ticket, je fourni ci-dessous un exemple de Markdown, et son rendu HTML ; l'idée est de modifier la feuille de style du site afin d'obtenir le rendu souhaité (à savoir `hl_lines` donne des lignes surlignées, et `linenostart` change le numéro de début de la ligne).

### Markdown utilisé

````markdown
```python linenostart=2 hl_lines=2-3
def main():
  print('It's amazing!')

def unused():
  print('Please use me!')
```
````

### HTML généré (oui, c'est brut)

```html
<div class="hljs-code-div"><div class="hljs-line-numbers"><span data-count="2" class="hll"></span><span data-count="3" class="hll"></span><span data-count="4"></span><span data-count="5"></span><span data-count="6"></span></div><pre><code class="hljs language-python"><span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">main</span><span class="hljs-params">()</span>:</span>
  print(<span class="hljs-string">'It'</span>s amazing!<span class="hljs-string">')

def unused():
  print('</span>Please use me!<span class="hljs-string">')
</span></code></pre></div>
```

## Quelques pistes & remarques

Toute l'information intéressante est stockée dans la *div* `hljs-line-numbers` ; actuellement, chaque `span` à l'intérieur de cet élément est compté, puis on y affiche le compte actuel :

```css
.main .content-container .article-content .hljs-code-div .hljs-line-numbers span:before,
.main .content-container .message-content .hljs-code-div .hljs-line-numbers span:before {
  counter-increment: line;
  content: counter(line);
  display: block;
}
```

Afin de tenir compte de `linenostart`, la modification est très simple, et consiste à afficher le numéro calculé par le moteur de rendu (dans `data-count`) : 

```css
.main .content-container .article-content .hljs-code-div .hljs-line-numbers span:not([data-count]):before,
.main .content-container .message-content .hljs-code-div .hljs-line-numbers span:not([data-count]):before {
  counter-increment: line;
  content: counter(line);
  display: block;
}

.main .content-container .article-content .hljs-code-div .hljs-line-numbers span[data-count]:before,
.main .content-container .message-content .hljs-code-div .hljs-line-numbers span[data-count]:before {
  content: attr(data-count);
  display: block;
}
```

Notons que pour la compatibilité avec les anciens rendus, les *span* n'ayant pas l'attribut `data-count` s'incrémentent normalement.

La gestion de `linenostart` est donc plus ou moins triviale, mais il manque le plus important : `hl_lines`, et là je n'ai pas vraiment d'idée de comment faire pour l'afficher correctement... Remarquons bien que la classe `hll`, correspondant aux lignes mises en évidences, est ajoutée aux numéros de ligne, et pas à la ligne entière ; toutefois, ces numéros sont alignés avec la ligne, il existe donc sans doute une solution, peut-être même triviale, pour régler le problème.
